# Generated by Django 4.2.21 on 2025-05-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuitem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='named_url',
            field=models.CharField(blank=True, help_text='Name of the URL pattern defined in urls.py', max_length=100),
        ),
    ]
